Hier könnt ihr den entsprechenden Namen für das jeweilige Level eines Rüstungsteil finden.
Level 01 - Multiplex
Level 02 - Vermodert
Level 03 - Beschädigt
Level 04 - Schartig
Level 05 - Ramponiert
Level 06 - Schlecht
Level 07 - Gebraucht
Level 08 - Gelb
Level 09 - Grün
Level 10 - Rot
Level 11 - Blau
Level 12 - Oktarin
Level 13 - Braun
Level 14 - Türkis
Level 15 - Schwarz
Level 16 - Eisern
Level 17 - Silbern
Level 18 - Golden
Level 19 - Gut Erhalten
Level 20 - Kräftig
Level 21 - Stark
Level 22 - Schnell
Level 23 - Flink
Level 24 - Vibrierend
Level 25 - Schädlich
Level 26 - Lärmend
Level 27 - Strahlend
Level 28 - Beißend
Level 29 - Nagend
Level 30 - Brummend
Level 31 - Kreischend
Level 32 - Siedend
Level 33 - Kochend
Level 34 - Springend
Level 35 - Brodelnd
Level 36 - Würgend
Level 37 - Verachtend
Level 38 - Anmaßend
Level 39 - Blühend
Level 40 - Brüllend
Level 41 - Lachend
Level 42 - Verspottend
Level 43 - Ätzend
Level 44 - Auflösend
Level 45 - Zersetzend
Level 46 - Grübelnd
Level 47 - Blinkend
Level 48 - Summend
Level 49 - Spuckend
Level 50 - Zerstückelnd
Level 51 - Spaltend
Level 52 - Vernichtend
Level 53 - Tödlich
Level 54 - Funkelnd
Level 55 - Gleißend
Level 56 - Blitzend
Level 57 - Schockend
Level 58 - Kalt
Level 59 - Eisig
Level 60 - Einfrierend
Level 61 - Qualmend
Level 62 - Funkend
Level 63 - Flackernd
Level 64 - Heiß
Level 65 - Sengend
Level 66 - Lodernd
Level 67 - Feurig
Level 68 - Flammend
Level 69 - Unheilig
Level 70 - Heilig