<?php 
unset($indexdata);
$index=0;
$indexdata[$index][0]='Arena';//titel
$indexdata[$index][1]=0;//id
$index++;
$indexdata[$index][0]='Arenaheiltrank';//titel
$indexdata[$index][1]=1;//id
$index++;
$indexdata[$index][0]='Auktionshaus';//titel
$indexdata[$index][1]=2;//id
$index++;
$indexdata[$index][0]='Brunnen';//titel
$indexdata[$index][1]=3;//id
$index++;
$indexdata[$index][0]='B&auml;ckerei';//titel
$indexdata[$index][1]=4;//id
$index++;
$indexdata[$index][0]='Destille';//titel
$indexdata[$index][1]=5;//id
$index++;
$indexdata[$index][0]='Erzmine';//titel
$indexdata[$index][1]=6;//id
$index++;
$indexdata[$index][0]='Erzschmelze';//titel
$indexdata[$index][1]=7;//id
$index++;
$indexdata[$index][0]='Getreidefarm';//titel
$indexdata[$index][1]=8;//id
$index++;
$indexdata[$index][0]='Heldengrundstein';//titel
$indexdata[$index][1]=9;//id
$index++;
$indexdata[$index][0]='Heldenturm';//titel
$indexdata[$index][1]=10;//id
$index++;
$indexdata[$index][0]='Holzf&auml;llerh&uuml;tte';//titel
$indexdata[$index][1]=11;//id
$index++;
$indexdata[$index][0]='Levelbezeichnung R&uuml;stungsteile';//titel
$indexdata[$index][1]=12;//id
$index++;
$indexdata[$index][0]='Magier Zelsus';//titel
$indexdata[$index][1]=13;//id
$index++;
$indexdata[$index][0]='M&ouml;nch Alandar';//titel
$indexdata[$index][1]=14;//id
$index++;
$indexdata[$index][0]='Orlandos Gemischtwaren';//titel
$indexdata[$index][1]=15;//id
$index++;
$indexdata[$index][0]='Portale';//titel
$indexdata[$index][1]=16;//id
$index++;
$indexdata[$index][0]='Quests';//titel
$indexdata[$index][1]=17;//id
$index++;
$indexdata[$index][0]='Rohstoffe und Geb&auml;ude';//titel
$indexdata[$index][1]=18;//id
$index++;
$indexdata[$index][0]='Ruinen';//titel
$indexdata[$index][1]=19;//id
$index++;
$indexdata[$index][0]='Sol-Altair-Stein';//titel
$indexdata[$index][1]=20;//id
$index++;
$indexdata[$index][0]='Steinbruch';//titel
$indexdata[$index][1]=21;//id
$index++;
$indexdata[$index][0]='Tyran-Selting-Stein';//titel
$indexdata[$index][1]=22;//id
$index++;
$indexdata[$index][0]='Waldmond';//titel
$indexdata[$index][1]=23;//id
$index++;
$indexdata[$index][0]='Windm&uuml;hle';//titel
$indexdata[$index][1]=24;//id
?>