<?php 
unset($indexdata);
$index=0;
$indexdata[$index][0]='Das Spiel';//titel
$indexdata[$index][1]=1;//id
$index++;
$indexdata[$index][0]='Das Universum';//titel
$indexdata[$index][1]=68;//id
$index++;
$indexdata[$index][0]='Abkürzungen';//titel
$indexdata[$index][1]=0;//id
$index++;
$indexdata[$index][0]='Aliens';//titel
$indexdata[$index][1]=2;//id
$index++;
$indexdata[$index][0]='Allianz';//titel
$indexdata[$index][1]=3;//id
$index++;
$indexdata[$index][0]='Artefakte';//titel
$indexdata[$index][1]=5;//id
$index++;
$indexdata[$index][0]='Auktion';//titel
$indexdata[$index][1]=6;//id
$index++;
$indexdata[$index][0]='Bashen';//titel
$indexdata[$index][1]=8;//id
$index++;
$indexdata[$index][0]='Basiskommandant(BK)';//titel
$indexdata[$index][1]=7;//id
$index++;
$indexdata[$index][0]='Basisschiff';//titel
$indexdata[$index][1]=9;//id
$index++;
$indexdata[$index][0]='Battleground (BG)';//titel
$indexdata[$index][1]=72;//id
$index++;
$indexdata[$index][0]='Battleround (BR)';//titel
$indexdata[$index][1]=76;//id
$index++;
$indexdata[$index][0]='Bonuspunkte';//titel
$indexdata[$index][1]=56;//id
$index++;
$indexdata[$index][0]='Bug';//titel
$indexdata[$index][1]=10;//id
$index++;
$indexdata[$index][0]='Cheaten';//titel
$indexdata[$index][1]=11;//id
$index++;
$indexdata[$index][0]='Counter';//titel
$indexdata[$index][1]=12;//id
/*
$index++;
$indexdata[$index][0]='DE-Zeitung';//titel
$indexdata[$index][1]=13;//id
*/
$index++;
$indexdata[$index][0]='DE Zeit/Ticks';//titel
$indexdata[$index][1]=14;//id
$index++;
$indexdata[$index][0]='Deff/Verteidigung';//titel
$indexdata[$index][1]=15;//id
$index++;
$indexdata[$index][0]='Deffbund';//titel
$indexdata[$index][1]=16;//id
/*
$index++;
$indexdata[$index][0]='EFTA-Projekt';//titel
$indexdata[$index][1]=18;//id
*/
$index++;
$indexdata[$index][0]='ERBAUER';//titel
$indexdata[$index][1]=69;//id
$index++;
$indexdata[$index][0]='Errungenschaften';//titel
$indexdata[$index][1]=19;//id
$index++;
$indexdata[$index][0]='Erste Schritte';//titel
$indexdata[$index][1]=20;//id
$index++;
$indexdata[$index][0]='FAQ';//titel
$indexdata[$index][1]=22;//id
$index++;
$indexdata[$index][0]='Flotte';//titel
$indexdata[$index][1]=23;//id
$index++;
$indexdata[$index][0]='Galaxie';//titel
$indexdata[$index][1]=25;//id
$index++;
$indexdata[$index][0]='Geheimdienst';//titel
$indexdata[$index][1]=27;//id
$index++;
$indexdata[$index][0]='Handelspunkte';//titel
$indexdata[$index][1]=30;//id
$index++;
$indexdata[$index][0]='Hyperfunk';//titel
$indexdata[$index][1]=31;//id
$index++;
$indexdata[$index][0]='IRC';//titel
$indexdata[$index][1]=32;//id
$index++;
$indexdata[$index][0]='Jagdbootsupport';//titel
$indexdata[$index][1]=33;//id
$index++;
$indexdata[$index][0]='Jägersupport';//titel
$indexdata[$index][1]=34;//id
$index++;
$indexdata[$index][0]='Kampfscript';//titel
$indexdata[$index][1]=35;//id
$index++;
$indexdata[$index][0]='Kampftick';//titel
$indexdata[$index][1]=36;//id
$index++;
$indexdata[$index][0]='Kollektor';//titel
$indexdata[$index][1]=37;//id
$index++;
$indexdata[$index][0]='Kopfgeld';//titel
$indexdata[$index][1]=73;//id
$index++;
$indexdata[$index][0]='Kristallpalast';//titel
$indexdata[$index][1]=38;//id
$index++;
$indexdata[$index][0]='Militär/Flotten';//titel
$indexdata[$index][1]=39;//id
$index++;
$indexdata[$index][0]='Missionen/Handel';//titel
$indexdata[$index][1]=29;//id
$index++;
$indexdata[$index][0]='Multiuser';//titel
$indexdata[$index][1]=40;//id
$index++;
$indexdata[$index][0]='Nachrichten';//titel
$indexdata[$index][1]=41;//id
$index++;
$indexdata[$index][0]='Optionen';//titel
$indexdata[$index][1]=42;//id
$index++;
$indexdata[$index][0]='Planetarer Rohstoffertrag';//titel
$indexdata[$index][1]=28;//id
$index++;
$indexdata[$index][0]='Premiumaccount';//titel
$indexdata[$index][1]=44;//id
$index++;
$indexdata[$index][0]='Produktion';//titel
$indexdata[$index][1]=45;//id
$index++;
$indexdata[$index][0]='Punkte';//titel
$indexdata[$index][1]=46;//id
$index++;
$indexdata[$index][0]='Ränge';//titel
$indexdata[$index][1]=52;//id
$index++;
$indexdata[$index][0]='Rangliste';//titel
$indexdata[$index][1]=47;//id
$index++;
$indexdata[$index][0]='Rassen';//titel
$indexdata[$index][1]=21;//id
$index++;
$indexdata[$index][0]='Reset';//titel
$indexdata[$index][1]=48;//id
$index++;
$indexdata[$index][0]='Ressourcen/Rohstoffe';//titel
$indexdata[$index][1]=49;//id
$index++;
$indexdata[$index][0]='Rohstoffumwandler';//titel
$indexdata[$index][1]=50;//id
$index++;
$indexdata[$index][0]='Runde';//titel
$indexdata[$index][1]=51;//id
$index++;
$indexdata[$index][0]='Schlachtschiffrecycling';//titel
$indexdata[$index][1]=74;//id
$index++;
$indexdata[$index][0]='Schlachtschiffsupport';//titel
$indexdata[$index][1]=53;//id
$index++;
$indexdata[$index][0]='Schwarzmarkt';//titel
$indexdata[$index][1]=54;//id
$index++;
$indexdata[$index][0]='Sektor';//titel
$indexdata[$index][1]=4;//id
$index++;
$indexdata[$index][0]='Sektorbund';//titel
$indexdata[$index][1]=55;//id
/*
$index++;
$indexdata[$index][0]='Sektorforum';//titel
$indexdata[$index][1]=57;//id
*/
$index++;
$indexdata[$index][0]='Sektorgebäude';//titel
$indexdata[$index][1]=58;//id
$index++;
$indexdata[$index][0]='Sektorkampf';//titel
$indexdata[$index][1]=59;//id
$index++;
$indexdata[$index][0]='Sektorkollektoren';//titel
$indexdata[$index][1]=77;//id
$index++;
$indexdata[$index][0]='Sektorkommandant';//titel
$indexdata[$index][1]=61;//id
$index++;
$indexdata[$index][0]='Sektorlager';//titel
$indexdata[$index][1]=60;//id
$index++;
$indexdata[$index][0]='Sektorpolitik';//titel
$indexdata[$index][1]=43;//id
$index++;
$indexdata[$index][0]='Sektorstatus';//titel
$indexdata[$index][1]=62;//id
$index++;
$indexdata[$index][0]='Server';//titel
$indexdata[$index][1]=63;//id
$index++;
$indexdata[$index][0]='Spezialisierung';//titel
$indexdata[$index][1]=75;//id
$index++;
$indexdata[$index][0]='Systemvoraussetzungen';//titel
$indexdata[$index][1]=70;//id
$index++;
$indexdata[$index][0]='Technologien/Forschungen';//titel
$indexdata[$index][1]=24;//id
$index++;
$indexdata[$index][0]='Technologien/Gebäude';//titel
$indexdata[$index][1]=26;//id
$index++;
$indexdata[$index][0]='Umfragen';//titel
$indexdata[$index][1]=67;//id
$index++;
$indexdata[$index][0]='Vergessene Systeme';//titel
$indexdata[$index][1]=71;//id
/*
$index++;
$indexdata[$index][0]='Verteidigung';//titel
$indexdata[$index][1]=64;//id
$index++;
$indexdata[$index][0]='Waffen';//titel
$indexdata[$index][1]=17;//id
*/
$index++;
$indexdata[$index][0]='Wellenangriff';//titel
$indexdata[$index][1]=65;//id
$index++;
$indexdata[$index][0]='Zufallsereignis';//titel
$indexdata[$index][1]=66;//id

?>