<?php 
unset($indexdata);
$index=0;
$indexdata[$index][0]='Schnelleinstieg';//titel
$indexdata[$index][1]=0;//id
$index++;
$indexdata[$index][0]='Geschichte';//titel
$indexdata[$index][1]=11;//id
$index++;
$indexdata[$index][0]='Charakter';//titel
$indexdata[$index][1]=1;//id
$index++;
$indexdata[$index][0]='Nachrichten';//titel
$indexdata[$index][1]=2;//id
$index++;
$indexdata[$index][0]='Abenteuer';//titel
$indexdata[$index][1]=3;//id
$index++;
$indexdata[$index][0]='Feldzug';//titel
$indexdata[$index][1]=4;//id
$index++;
$indexdata[$index][0]='Bergwerk';//titel
$indexdata[$index][1]=5;//id
$index++;
$indexdata[$index][0]='Marktplatz';//titel
$indexdata[$index][1]=6;//id
$index++;
$indexdata[$index][0]='Gilde';//titel
$indexdata[$index][1]=7;//id
$index++;
$indexdata[$index][0]='Gildenfeldzug';//titel
$indexdata[$index][1]=8;//id
$index++;
$indexdata[$index][0]='Ehrenplatz';//titel
$indexdata[$index][1]=9;//id
$index++;
$indexdata[$index][0]='Optionen';//titel
$indexdata[$index][1]=10;//id

?>